### ISSUE TITLE
Update About Us with new staff

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textualize.io#107]
https://www.textualize.io/about-us

@davep Could you provide us with a mugshot and a short bio.

**Comment by davep** [comment]
Is my usual mugshot okay or do we need to subject everyone to my unmasked face?

**Comment by davep** [comment]
Assuming my usual is okay, here's a copy:

![IMG_1338](https://user-images.githubusercontent.com/28237/194944615-f1e21f4d-9eb3-41e2-b5a5-df4754b480b1.jpeg)

And here's my attempt at a short bio:

*Hey! I'm Dave. My love of programming started 40 years ago, with a Sinclair ZX81, and I've been making a living from it for well over 30 years now. I've yet to get bored of it. My experience has run through many platforms, and many languages, and my career has taken me into many areas including fashion retail, complaints handling, banking, aeronautical engineering and bioinformatics. Having started out building DOS systems, then moving on to Windows and then the web, it seems I'm back in the land of text again!*

*Outside of coding you'll often find me gaming, almost always in VR, and when my head isn't inside a VR headset I'm normally out walking or running.*

Is that in the right spirit?

Twitter link is of course https://twitter.com/davepdotorg
