### ISSUE TITLE
Expandable videos

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textualize.io#63]
I suspect some of the videos don't look good on a non-retina screen, i.e. what most people have these days.

We should probably have some mechanism to expand the video to full-screen (or near enough). 

Not sure what that mechanism should be. A button, on hover? Open to suggestions...

**Comment by DrBenton** [comment]
Note sure how handy the hover would be on a mobile device? I guess it could be a tiny button right below the video?

On the technical side we could use this package: https://github.com/snakesilk/react-fullscreen#readme 
(thin React wrapper around [this lib](https://github.com/rafgraph/fscreen#readme) - itself a wrapper around the browsers' native Fullscreen API, which has the following downside: _"support for this API varies somewhat across browsers, with many requiring vendor prefixes and/or not implementing the latest specification."_ (MDN))
