### ISSUE TITLE
Gallery Project page

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textualize.io#74]
I think that projects in the gallery should also have a unique page of their own. Beneficial for SEO I suspect, and also that we can have a URL for one specific project.

I'm wondering if the frontmatter should have a "Descrption" field which should be one or two sentences, leaving the body of the md for the gallery item page.

**Comment by DrBenton** [comment]
> I'm wondering if the frontmatter should have a "Descrption" field which should be one or two sentences, leaving the body of the md for the gallery item page.

@willmcgugan That sounds like the right way to do it indeed! However, I wonder which content we should use for the existing projects we have in the gallery?
Shall we move their content to this new `description` YAML field, and fall back to it if there is no body? (in which case the current projects' pages content will be the same on their dedicated page than on the gallery index pages)

**Comment by DrBenton** [comment]
Depends on some CSS factorisations made during the implementation of #95 - so as long as this other task is blocked this one is blocked too :slightly_smiling_face:

**Comment by DrBenton** [comment]
As discussed:
 - [ ] We should fix the GH stars display of a "Project using..." for light theme
