### ISSUE TITLE
Host images on our own domain

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textualize.io#93]
We should host the profile images on about-us on our own domain.

https://twitter.com/AdamChainz/status/1537040997489811458

**Comment by DrBenton** [comment]
I'm a Firefox user myself, but I didn't notice that! But I can reproduce indeed if I set the protection to "strict" mode  - which comes with a clear warning about that kind of stuff :slightly_smiling_face: 

Let's fix this! :wrench: 

![Screenshot from 2022-06-15 15-03-08](https://user-images.githubusercontent.com/722388/173846763-2ecd0d06-fb2b-4cc9-b86b-ba9ede424b39.png)
