### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textualize.io#95]
We need a blog page on Textualize.io

Can be fairly rudimentary. Content with forward / back links, and some kind of index showing recent posts.

**Comment by DrBenton** [comment]
We're going to need a first blog post before we can PR-and-merge the work done on the blog - the ball is in your court Will :tennis:  :slightly_smiling_face:
The Markdown file for this blog post must replace those test ones:
https://github.com/Textualize/textualize.io/tree/add-blog-space/data/blog

**Comment by DrBenton** [comment]
As discussed:
 - Let's remove the last blog post display from the homepage for the moment - Google (and users) should see the blog by following the link in the footer anyway
 - Maybe a megaphone icon would be better for this footer link?
